name: mdformat-action
author: ydah <t.yudai92@gmail.com>
description: Github Action for linting markdown files using mdformat.
branding:
  icon: 'sliders'
  color: 'blue'
inputs:
  mdformat_file_or_dir:
    description: 'File or Directory to do mdformat on'
    required: false
    default: '.'
  mdformat_number:
    description: 'Apply consecutive numbering to ordered lists'
    required: false
    default: '0'
  mdformat_wrap:
    description: 'Paragraph word wrap mode (default: keep)'
    required: false
    default: 'keep'
  mdformat_end_of_line:
    description: 'Output file line ending mode (default: lf)'
    required: false
    default: 'lf'
runs:
  using: 'docker'
  image: 'Dockerfile'
